artifact_uri: /Users/lakshraj/Documents/Projects/gridmind/mlruns/414089671536392554/1c4feeb7b9dc4c9c9a7fcbfaaff5153d/artifacts
end_time: 1783955533415
entry_point_name: ''
experiment_id: '414089671536392554'
lifecycle_stage: active
run_id: 1c4feeb7b9dc4c9c9a7fcbfaaff5153d
run_name: seasonal_naive_average_24h_168h
source_name: ''
source_type: 4
source_version: ''
start_time: 1783955533407
status: 3
tags: []
user_id: lakshraj
