artifact_uri: /Users/lakshraj/Documents/Projects/gridmind/mlruns/414089671536392554/a1cfc593fb8e41fcadf7ad4d1a717304/artifacts
end_time: 1783957760965
entry_point_name: ''
experiment_id: '414089671536392554'
lifecycle_stage: active
run_id: a1cfc593fb8e41fcadf7ad4d1a717304
run_name: seasonal_naive_24h
source_name: ''
source_type: 4
source_version: ''
start_time: 1783957760957
status: 3
tags: []
user_id: lakshraj
